language: objective-c

os: osx
osx_image: xcode8.3

# Turn off email notifications entirely:
notifications:
  email: false
  
before_install:
  - brew update
  - brew install shellcheck

script:
  - ./test.sh